FROM jenkins

USER root
RUN apt-get update -y
RUN apt-get install -y  tar wget git openjdk-7-jdk autoconf libtool build-essential python-dev libcurl4-nss-dev libsasl2-dev libsasl2-modules maven libapr1-dev libsvn-dev
USER jenkins
